%%{init: {
  "theme": "base",
    "flowchart": {
        "htmlLabels": false
    },
  "themeVariables": {
    "fontFamily": "Arial",
    "fontSize": "14px",
    "primaryColor": "#ffffff",
    "primaryTextColor": "#000000",
    "primaryBorderColor": "#000000",
    "lineColor": "#000000",
    "secondaryColor": "#ffffff",
    "tertiaryColor": "#ffffff",
    "noteBkgColor": "#ffffff",
    "noteTextColor": "#000000",
    "textColor": "#000000"
  },
  "flowchart": { "curve": "linear" }
}}%%

flowchart LR
  Gt[Lattice State at epoch t] --> D[Delta at epoch t]
  D --> Gt1[Lattice State at epoch t plus 1]
  N1[Delta stores only changed cells] --- D
  N2[Unchanged cells are omitted] --- D

  classDef op stroke:#000,stroke-width:2px,fill:#fff,color:#000;